node {
   def commit_id
   stage('GIT Checkout') {
     checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/yanivomc/docker-cicd']]])
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       '''
       cd basics
       npm install --only=dev
       npm test
       '''
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockeryaniv') {
       def app = docker.build("yanivomc/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: """docker rm docker_test
      docker run --rm -tid --name docker_test -p 3000 yanivomc/docker-nodejs-demo:latest
      docker kill docker_test
      echo Commit ID: ${commit_id}
      """
     }
   }